language: node_js
node_js:
  - "node"
cache: yarn
jobs:
  include:
    - stage: test
      script: 'yarn run test & yarn danger'
    - stage: expo deploy
      if: type IN (push, pull_request)
      os: osx
      script:
        - brew install watchman
        - sudo sysctl -w kern.maxfiles=5242880
        - sudo sysctl -w kern.maxfilesperproc=524288
        - yarn appr