language: node_js
node_js: '8.7.0'
cache: yarn
stages:
  - name: test
    if: type IN (push)
  - name: pr deploy
    if: type IN (pull_request)
  - name: deploy
    if: branch = master AND NOT (type IN (pull_request))
jobs:
  include:
    - stage: test
      script:
        - yarn danger
        - yarn run test
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - stage: pr deploy
      sudo: required
      script:
        - sudo sysctl fs.inotify.max_user_watches=524288
        - sudo sysctl fs.inotify.max_queued_events=524288
        - sudo sysctl -p
        - travis_wait yarn run ci-deploy
    - stage: deploy
      # 1: deploy storybook to gh-pages
      script: yarn run build-storybook
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: storybook-static
    - # 2: deploy master to expo
      sudo: required
      script:
        - sudo sysctl fs.inotify.max_user_watches=524288
        - sudo sysctl fs.inotify.max_queued_events=524288
        - sudo sysctl -p
        - travis_wait yarn run ci-deploy
