language: node_js
node_js:
  - "node"
cache: yarn
jobs:
  include:
    - stage: test
      script: 'yarn run test'
    - stage: deploy to expo
      if: type IN (push, pull_request)
      script: 'yarn appr'