language: node_js
node_js:
  - "node"
cache: yarn
jobs:
  include:
    - stage: test
      script: 'yarn run test'
    - # we only want to deploy to expo if in pull request
      if: type IN (pull_request)
      script: 'yarn appr'