language: node_js
node_js: '8.7.0'
cache: yarn
stages:
  - test
  - name: deploy
    if: branch = master AND type NOT IN (push, pull_request)
jobs:
  include:
    - stage: test
      script:
        - yarn danger
        - yarn run test
    - # Run expo build in parallel (same stage)
      if: type IN (push, pull_request)
      sudo: required
      script:
        - sudo sysctl fs.inotify.max_user_watches=524288
        - sudo sysctl fs.inotify.max_queued_events=524288
        - sudo sysctl -p
        - travis_wait yarn run appr
    - stage: deploy
      # 1: deploy storybook to gh-pages
      script: yarn run build-storybook
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: storybook-static
    - # 2: deploy master to expo
      script: skip
      sudo: required
      deploy:
        provider: script
        script:
          - sudo sysctl fs.inotify.max_user_watches=524288
          - sudo sysctl fs.inotify.max_queued_events=524288
          - sudo sysctl -p
          - travis_wait yarn run appr
